#!/bin/bash
# package python program to .app

echo "Running script to package Canvas app..."

exe=$(which python)
if [ "$exe" != $HOME/.virtualenvs/canvas-shared/bin/python ]; then
    echo "Must be run in 'flask' virtualenv!";
    exit 1;
fi

# clean directories
rm -rf build dist

python docs/convert_readme.py

# PRODUCTION VERSION

pyinstaller src/main.py \
    --windowed \
    --name Canvas\ Browser \
    --icon icons/icon.icns \
    --add-data 'icons/*.png:icons' \
    --add-data 'docs/README.html:docs'

rm -rf dist/Canvas\ Browser/

cp docs/README.html dist/

hdiutil create -volname Canvas\ Browser -srcfolder dist -ov Canvas\ Browser.dmg 

# DEBUG VERSION

# pyinstaller main.py \
#     --name CanvasBrowser \
#     --icon icons/icon.icns \
#     --add-data 'icons/*.png:icons' \
#     --add-data 'docs/README.html:docs'
#     --log-level DEBUG \
#     --debug all